### ISSUE TITLE
RS02/03 header detection

### ISSUE THREAD

**Issue by Funodav** [speed47/dvdisaster#19] opened 2021-01-11 17:50 UTC
Hi, first thank you for reviving this project :)
Today to test it, I tried to create an rs03 augmented image.

But after burning it with ImgBurn and re-read the disc with dvdisaster I found that it can't see the augmented part.

0.79.6pl4 : 
![0](https://user-images.githubusercontent.com/22561067/104218365-ec0d5600-543c-11eb-9fe9-8384a3b97b76.png)

0.79.6pl4 : (Recover RS03 headers enable)
![1](https://user-images.githubusercontent.com/22561067/104218516-25de5c80-543d-11eb-89fe-5540d1b82747.png)

Is this behaviour normal ?

on a side note with a blank cd I get this :
![2](https://user-images.githubusercontent.com/22561067/104220617-101e6680-5440-11eb-8e40-5e80b05340ae.png)

(The old version) :
![3](https://user-images.githubusercontent.com/22561067/104220676-21677300-5440-11eb-8baf-f9fb62cb861f.png)

ps: that it is the same thing with RS02 and this version.
on 0.72 the RS02 disc is detected without changing settings.

Again thank you for the git.

**Comment by speed47** [comment] 2021-01-11 22:24
Hello, and thanks for your bug report!

About the "SetLabelText(...) failed" message you get on the medium info about RS03, I can reproduce it successfully: I'll have to find out why this happens, but it's only a display glitch, the "failed" is not about the RS03 data, it's about "SetLabelText" which is the function to update this info on the window. I tested on the command-line version to be sure, and there is no "failed" here. This is a cosmetic bug, but I'll check into it.

About the error you get with the blank CD, I can't reproduce it, but maybe something about your drive/CD combination is not handled correctly in this new version. I didn't modify anything around that part w.r.t the original upstream version, but I can try to have a look. Could you run the following on a cmd.exe window, capture the output and paste it here ?

`dvdisaster.exe -d F: -v --ignore-fatal-sense --medium-info`

**Comment by Funodav** [comment] 2021-01-11 22:43
Thanks for the reply 👍 

On 0.79.6 : 
https://pastebin.com/sr8zhjap

On 0.72 (verbose log) :
https://pastebin.com/rBqE3Dpb

**Comment by speed47** [comment] 2021-01-12 18:15
Tracked down the two bugs. They were present since a long time upstream. I should release ``pl5`` tonight :)

**Comment by speed47** [comment] 2021-01-12 21:06
Can you try the latest release (pl5)?

**Comment by Funodav** [comment] 2021-01-12 21:59
on launch in the CMD : "(dvdisaster.exe:4480): Gtk-WARNING **: 22:12:43.050: Unable to locate theme engine in module_path: "wimp","

with blank cd :
![4](https://user-images.githubusercontent.com/22561067/104375333-8051e880-5523-11eb-99a2-1e55d4a117bc.png)


RS02 (0.79.6 pl5) : 
![4 1](https://user-images.githubusercontent.com/22561067/104377006-1850d180-5526-11eb-861d-0ede42e4e704.png)
![5](https://user-images.githubusercontent.com/22561067/104377030-20107600-5526-11eb-8a23-623070535108.png)

RS02 (0.79.6 pl5) : 
![7](https://user-images.githubusercontent.com/22561067/104377316-99a86400-5526-11eb-8aa8-c24e9106a815.png)
![8](https://user-images.githubusercontent.com/22561067/104377454-d2e0d400-5526-11eb-8aef-d13264841d36.png)

RS02 (0.72 pl3) :
![6](https://user-images.githubusercontent.com/22561067/104377033-230b6680-5526-11eb-9f32-fe9551dc2387.png)

In my case (I don't kown why) I need to force the "deep search" for dvdisaster to find the RS02/RS03 augmented portion (maybe a different approach was used with 0.79.6 and it doesn't like my drive)

RS03 (0.79.6 pl5) :
![4 1](https://user-images.githubusercontent.com/22561067/104377006-1850d180-5526-11eb-861d-0ede42e4e704.png)
![9](https://user-images.githubusercontent.com/22561067/104378943-06246280-5529-11eb-8a64-1fa57e5719c7.png)

RS03 (0.79.6 pl5) :
![10](https://user-images.githubusercontent.com/22561067/104378986-163c4200-5529-11eb-9220-85a898abfb0f.png)
![11](https://user-images.githubusercontent.com/22561067/104378998-19373280-5529-11eb-8f79-f123f3332b28.png)

Sorry for the huge amount of screenshots,

**Comment by speed47** [comment] 2021-01-13 12:40
> on launch in the CMD : "(dvdisaster.exe:4480): Gtk-WARNING **: 22:12:43.050: Unable to locate theme engine in module_path: "wimp","

This was an error in the automated packaging of the release, the "gtk-2.0" folder was missing in "lib/", it has already been fixed (if you re-download the release, you should no longer have this)

> with blank cd :

Found another corner case with blank CD medium-info, can you try this version?
[dvdisaster-v0.79.6-pl5-test1-win64-portable.zip](https://github.com/speed47/dvdisaster/files/5808602/dvdisaster-v0.79.6-pl5-test1-win64-portable.zip)

> In my case (I don't kown why) I need to force the "deep search" for dvdisaster to find the RS02/RS03 augmented portion (maybe a different approach was used with 0.79.6 and it doesn't like my drive)

That's strange, I tried to reproduce this with RS02, but it works correctly on my end, without deep search:
![rs02ok](https://user-images.githubusercontent.com/218502/104453409-aa97ba80-55a4-11eb-861d-0f50b94022d0.PNG)

Could you paste somewhere the complete output of this?
`./dvdisaster -d g: --medium-info -v > output.txt`

It might contain some clues. You can remove the CD label name from the output if you want.

**Comment by Funodav** [comment] 2021-01-13 13:22
Thanks for your work,
don't worry about the CD label :)

For the blank CD it is perfect:

![12](https://user-images.githubusercontent.com/22561067/104456462-fa788080-55a8-11eb-890f-df1610d5c389.png)
but if I want to query the blank size for RS02
![13](https://user-images.githubusercontent.com/22561067/104456874-9b673b80-55a9-11eb-8e5e-e8031f4b40c1.png)

For my RS03 cd :
https://pastebin.com/LPCb2EXw

**Comment by speed47** [comment] 2021-01-13 18:00
> For the blank CD it is perfect:

Good!

> but if I want to query the blank size for RS02

Indeed: I've just added the same logic than the one for "medium info", and it works now. This will be in `pl6` :)

> For my RS03 cd :
> https://pastebin.com/LPCb2EXw

That's strange, the RS03 signature is not found where the program expects it (which is, right after the "normal" data part of the untouched .iso). If you try the same command but with deep search, so I can see how the log file differs and at which sector it finally finds the RS03 signature?

`./dvdisaster -d d: --medium-info -v -a rs03 > output.txt`

**Comment by Funodav** [comment] 2021-01-13 22:24
https://pastebin.com/V9NN1QS9

**Comment by speed47** [comment] 2021-01-18 11:57
I don't reproduce your issue of requiring deep search for RS02 or RS03, that's strange.
From your pastebin, we see that

`Volume space size         : 182783 sectors`

And from the RS02 normal (non-deep) search code, we see that it should contain a signature at the first sector after the data part (hence sector number 182783 in your case), and also at this sector minus 150, so 182633 in your case.

However, it doesn't find any signature at those two locations, but does find the signature with deep search, at sector 183170.

Do you have this behavior with an old version too, or is it just from 0.79.6 onwards? Your drive shouldn't matter, but maybe this is something with respect to how your original ISO has been created. Can you share more info about this? Maybe I'll be able to reproduce if I can produce an ISO like yours. Do you enable UDF on it? Joliet? Or only ISO9660?

**Comment by Funodav** [comment] 2021-01-18 18:45
Ok I think you on the right track !!
I normaly make my iso with **ImgBurn** (I tested a buch of settings [UDF, ISO, Joliet...]) but no luck with 0.79.6,
Then I tried with an other soft (AnyBurn) just for the iso and Voilà !
![14](https://user-images.githubusercontent.com/22561067/104952060-107cab80-59c4-11eb-909c-190353894ab8.png)
i tried iso joliet and iso joliet + udf 
but the udf only yielded the same result

I know that on the old 0.72 pl3 (for rs02) does not exibit this (maybe it does a deep search by default)

I don't know what ImgBurn change in the iso that dvdisaster 0.79.6 [pl1->pl6] does not like.

**Comment by speed47** [comment] 2021-01-20 19:45
Okay, I get what happens. I'll go into details because that's also directed to my future self, as to not forget all the digging I've done, and the conclusions that were drawn :)

In fact this issue is not linked to 0.76.9 versions, as I can reproduce it also with an old 0.72 windows version: indeed an ImgBurn iso, augmented with RS02 (for example), doesn't get detected as augmented in medium-info if you don't enable exhaustive search. It turns out this is not a bug, it's "normal" behavior, at least how the original author intended, this will become apparent shortly.

When augmenting images with RS02 or RS03, dvdisaster is adding data of its own right after whatever data is contained in the iso file, up to the maximum projected medium size (CD, DVD, BD). The data in the iso file can contain ISO9660 structures, and/or Joliet, and/or Rock Ridge, and/or UDF, etc. It doesn't matter for dvdisaster, as it protects the file at the sector level. Now, what it does when exhaustive search is not ticked and is not implicitly forced (it is if you're hitting "verify" or "repair"), is that it reads the ISO9660 structure of the disc, and tries to read the sector right after the end of the data size as advertized by the ISO9660 structure. And, that's it. If this sector is not a dvdisaster RS02/RS03 signature, it'll guess the disc is not protected. Interestingly, the author noticed that some softwares sometimes produced ISO9660 structures advertising 150 sectors more data than the actual size, hence dvdisaster also checks 150 sectors before the end of the structure. So that's only two sector reads.

Now, what happens is that some softwares do add a few sectors after the ISO9660 structure, as it turns out ImgBurn does that for some reason. If you produce an UDF only image, then the software won't matter as no data size will be advertised by the non-existent ISO9660 structure. In that case non-exhaustive search reads no sector, and it has no chance of telling your your disc has been augmented.

What is called exhaustive search is in fact all the power of the dvdisaster algorithms looking for sectors where the added ECC data should be. For medium-info, the author didn't want to "force" this exhaustive search by default because it can produce dozens of sector reads at different portions of the disc, especially if, in the end, the disc is not augmented. This would produce some delay in the medium-info page for non-augmented disc, as the only way to tell is to look for all the proper places where the ECC headers should be, and when we've exhausted all the theoretical places and found nothing, then it must mean it's not augmented.

The name exhaustive search is misleading: I think the options should be called "only conduct a quick search of RS02/RS03 by default", which would only read 2 sectors max as I explained above, and the "exhaustive search" would just be the normal search, because that's what it is in the end: in verify / fix, this is the one that is used, and this is the only one that really matter to protect your discs.

I'm trying something: when exhaustive search is not enabled, read the 2 sectors according to ISO9660 (if present) as above, and if an augmented image is not found, begin an exhaustive search but only read up to 3 sectors more. From the few tests I've made with ImgBurn, it turns out the exhaustive search algorithm always found the augmented image after 1 sector read, so it doesn't add too much delay to the medium-info page, and is, I think, a good compromise.

**Comment by speed47** [comment] 2021-01-21 11:46
What is discussed above has been implemented in this test version: https://github.com/speed47/dvdisaster-test/releases/download/v0.79.6-pl6-test2/dvdisaster-v0.79.6-pl6-test2-win32-portable.zip

**Comment by Funodav** [comment] 2021-01-24 21:55
I think something isn't right 

ISO9660+Joliet+UDF from imgburn

no options:
https://pastebin.com/rsQAWGDi
![16](https://user-images.githubusercontent.com/22561067/105644686-217f5e00-5e97-11eb-926c-f460c459f479.png)

force RS03:
https://pastebin.com/NFbuksdC
![17](https://user-images.githubusercontent.com/22561067/105644693-293f0280-5e97-11eb-8cde-b846e07cddaa.png)

force RS02:
https://pastebin.com/if3Lkx15
![18](https://user-images.githubusercontent.com/22561067/105644700-2fcd7a00-5e97-11eb-86e2-deb2baf22b47.png)
skip...
![19](https://user-images.githubusercontent.com/22561067/105644704-32c86a80-5e97-11eb-8035-b0dc65450f39.png)

**Comment by speed47** [comment] 2021-01-26 19:11
Thanks for the feedback again! Here I make the assumption that on all your examples you've used the same disc with RS03.

> no options:
> https://pastebin.com/rsQAWGDi

The modification I've made to the original version to try to better find RS02 without doing exhaustive search doesn't seem to be enough to find RS03 signatures indeed. The "non exhaustive search" now tries 3 sectors at most (before it wasn't trying at all, and only worked on discs where the ISO9660 size was the same than the produced iso file, but it's not the case with imgburner and others as we've seen). For RS02 this seems enough but for RS03, not always. It took me a dozen tries to produce a disc with exactly the same number of sectors as the one in your example, to be sure we were looking at the same data, and with the RS03 exhaustive search (and some logs I've added to make it more explicit with the verbose mode), I can see that it took 88 sector reads to find the proper RS03 signature:

```
RS03RecognizeImage: No EH, entering exhaustive search
.. trying layer size 1409
Scanning layers for signatures.
- layer slice 0
RS03: try number = 1, reading sector 118356 == 118356
RS03: try number = 2, reading sector 119765 == 119765
...[cut]...
RS03: try number = 88, reading sector 240939 == 240939
** Success: sector 240939, rediscovered format with 83 roots
...augmented image found
```

So obviously 3 is not enough in this case. I'll see if I can make it better, but in any case this is as the author intended: don't read too many sectors on the "medium info" page, unless the user asked us to really look for the signatures ("exhaustive search"). Maybe this could be made more explicit in the GUI as to not make users "panic" if they don't see their augmented image in medium info with exhaustive search disabled.

> force RS03:
> https://pastebin.com/NFbuksdC

This one is strange because (excerpt from your paste):

> RS02Recognize: skipping exhaustive RS02 search, doing 3 sector reads only
> RS03RecognizeImage: skipping complete exhaustive RS03 search, doing 3 sector reads only

Here dvdisaster says that exhaustive search is disabled for RS02 and RS03, exactly as the above test, so this is why you're getting the same result. Note that the CLI version (I suppose that's what you've launched to get the text output?) does NOT read the configuration from the GUI options panel. With the image i've created to match yours, I do get the augmented image info in medium-info on the GUI with the RS03 exhaustive search enabled however. Could you double-check just to be sure?

> force RS02:
> https://pastebin.com/if3Lkx15

The message about the RS02 check taking a long time is to be expected, as you have RS03 on your image, so after a few sector reads (5 IIRC) and no RS02 signature found, it tells you that it might take some time to do all the remaining tries. But then finding the RS03 signature with RS03 exhaustive search disabled and RS02 exhaustive search enabled, I don't reproduce this either :(

I'll see if I can either get a better guess with RS03 exhaustive search disabled, or indicating in the GUI what to do if no augmented image is seen in medium-info (which doesn't mean there is not), for pl7.

In the meantime, I've put up a new test version with 2 changes:
- more logs around the RS03 exhaustive search (as in my log above)
- 2 new options in the CLI when debug mode is enabled: `--examine-rs02` and `--examine-rs03`. These are to force an exhaustive search in the medium-info CLI mode, as you can do with the GUI, hence:
`dvdisaster --debug --examine-rs03 -v -d H: --medium-info` should find your augmented image, as it should in the GUI with exhaustive search enabled.

https://github.com/speed47/dvdisaster-test/releases/download/v0.79.6-pl6-test3/dvdisaster-v0.79.6-pl6-test3-win32-portable.zip

**Comment by speed47** [comment] 2021-02-22 20:47
> [...] indicating in the GUI what to do if no augmented image is seen in medium-info (which doesn't mean there is not), for pl7.

Done in latest master branch. An "exhaustive search" button appears if no ECC data was found, and systematic exhaustive search is not enabled in the options.

**Comment by speed47** [comment] 2021-03-27 11:37
Considering this fixed, please reopen after testing with the latest version should any problem arise.

**Closed by speed47** 2021-03-27 11:37 UTC
